import "~/styles/globals.css";

import { type Metadata } from "next";

import { AvatarStoreProvider } from "~/providers/avatar-store-provider"
import Footer from "~/components/ui/footer";

import Navigation from "~/components/ui/navigation";

import Script from 'next/script'

import { TRPCReactProvider } from '~/trpc/react'
import { HydrateClient } from "~/trpc/server";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
      <TRPCReactProvider>
        <html lang="en" className="h-full w-full" >
          <body className="h-full w-full bg-black" >
            <HydrateClient>
              <AvatarStoreProvider>
                <Navigation/>
                {children}
                <Footer/>
              </AvatarStoreProvider>
            </HydrateClient>
          </body>
        </html>
      </TRPCReactProvider>
  );
}
